[package]
name = "image_manip"
version = "1.2.1"
authors = ["igorfs10 <igorfs10@gmail.com>"]
edition = "2018"
license = "gpl-v3"

[dependencies]
photon-rs = { git = "https://github.com/silvia-odwyer/photon/" }
toml = "^0.5.8"
serde = "^1.0.118"
rayon = "^1.5.0"
blake3 = "^0.3.7"
console = "^0.14.0"
chrono = "^0.4.19"

[profile.release]
lto = true

[profile.release.build-override]
opt-level = 3