[package]
name = "image_manip"
version = "1.0.0"
authors = ["igorfs10 <igorfs10@gmail.com>"]
edition = "2018"
license = "gpl-v3"

[dependencies]
photon-rs = { git = "https://github.com/silvia-odwyer/photon/" }
chrono = "^0.4"
toml = "^0.5.6"
serde = "^1.0.115"