[package]
name = "image_manip"
version = "1.1.1"
authors = ["igorfs10 <igorfs10@gmail.com>"]
edition = "2018"
license = "gpl-v3"

[dependencies]
photon-rs = { git = "https://github.com/silvia-odwyer/photon/" }
toml = "^0.5.6"
serde = "^1.0.116"
rayon = "^1.4.0"
blake3 = "^0.3.6"
colour = "^0.5.0"
chrono = "^0.4.18"