[package]
name = "image_manip"
version = "1.2.2"
authors = ["igorfs10 <igorfs10@gmail.com>"]
edition = "2018"
license = "gpl-v3"

[dependencies]
image = "0.23.14"
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
rayon = "1.5.1"
blake3 = "0.3.8"
console = "0.14.1"
chrono = "0.4.19"

[profile.release]
lto = true
opt-level = 3
codegen-units = 1